language: scala
sbt_args: 
   -sbt-version 0.13.1
scala:
   - 2.11.6
   - 2.11.5
   - 2.11.4
   - 2.11.1
   - 2.10.4
script:
  - sbt clean
  - sbt update
  - sbt compile
  - sbt test
  - sbt run
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
